version: "3"

volumes:
  onto:
    driver: local
  pgdata:
    driver: local
services:
  db:
    image: postgres-ontoserver
    container_name: ontoserver-db
    build:
      context: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  ontoserver:
    image: aehrc/ontoserver:latest
    container_name: ontoserver-onto
    depends_on:
      - db
    environment:
      - ONTOSERVER_INSECURE=true # handled by nginx
      - ontoserver.security.enabled=true
      - ontoserver.security.readOnly.fhir=false
      - ontoserver.security.readOnly.api=false
      - ontoserver.security.readOnly.synd=false
      - conformance.security.kinds=SMART-on-FHIR
      - conformance.security.description=This server uses OpenID Connect to authorize requests. Read-Only FHIR requests are NOT allowed.
      - conformance.security.authorize=https://athena.local/auth/realms/ontoserver/protocol/openid-connect/auth #<== CHANGE THIS SETTING
      - conformance.security.token=https://athena.local/auth/realms/ontoserver/protocol/openid-connect/token # <== CHANGE THIS SETTING
      - conformance.fhir.base=https://athena.local/ontoserver/fhir # <== CHANGE THIS SETTING
      - JAVA_OPTS=-Xmx4G
        # keycloak does not really support symmetric signing keys for JWTs using HS256 (rather, the key can not be extracted),
        # so that RS256 asymmetric crypto is used for key signing. The public key for RS256 can be obtained in the 'Realm Settings'
        # section for the chosen Realm, and then go to "Keys" and copy the Public Key via the button in the RS256 row.
        # Replace the public key in the line below, keeping the markers intact (with 5 leading and trailing dashes!).
        # CHANGE THIS SETTING
      - ontoserver.security.token.secret=-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApeS3BVDSzwmrKZqcQoTR8bZoaTcyFovmgDsRYclvbnJ10Jw7gM6epUenDyXuW3x0EZjkvA12SsvcPp1mLnY1qaLMb/4gLAWUgbjUif9wcWzQHe4SqzWMKHZAalszGkB9x045kYdFfLdVMAh1UQsB9CZFUEeKtR4GD85bllZQAG/NsDlCjNH119RS+qQUwB2eQiVcVDgkVCovbzB8olbdFw11s8/I1r/ZGGvEhxthHfqvX1o7JbXfqHu7lgQu+FE9f820ySXBQwJOnDR4MOsGJl2eT8t2cH4aqUxH/qO/a9oMl/3eu0ezkUq+L5cgYRJ4frvDlVoIZ4284aJSAPwdpwIDAQAB -----END PUBLIC KEY-----
  keycloak:
    image: ontoserver-keycloak
    container_name: ontoserver-keycloak
    build:
      context: ./keycloak
    depends_on:
      - db
    environment:
      - KEYCLOAK_USER_FILE=/opt/secrets/username.secret #<== CREATE THIS FILE
      - KEYCLOAK_PASSWORD_FILE=/opt/secrets/password.secret #<== CREATE THIS FILE
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - PROXY_ADDRESS_FORWARDING=true # essential for operating behind proxy!
  nginx:
    image: ontoserver-nginx
    container_name: ontoserver-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ontoserver
      - keycloak
